# Module: NumPy Assignments
## Lesson: NumPy
### Assignment 1: Array Creation and Manipulation

1. Create a NumPy array of shape (5, 5) filled with random integers between 1 and 20. Replace all the elements in the third column with 1.

In [31]:
import numpy as np

# Create a NumPy array of shape (5, 5) filled with random integers
array = np.random.randint(1, 21, size=(5, 5))
print("Original array:")
print(array)

# Replace all the elements in the third column with 1
array[:, 2] = 1
print("Modified array:")
print(array)

Original array:
[[ 8  1  4  9 20]
 [19 16 11  8 16]
 [12 17 14 11  2]
 [ 5 14  7 17  8]
 [ 4  3 16  9 16]]
Modified array:
[[ 8  1  1  9 20]
 [19 16  1  8 16]
 [12 17  1 11  2]
 [ 5 14  1 17  8]
 [ 4  3  1  9 16]]


2. Create a NumPy array of shape (4, 4) with values from 1 to 16. Replace the diagonal elements with 0.

In [37]:
import numpy as np

# Create a NumPy array of shape (4, 4) filled with random integers
array = np.random.randint(1, 17, size=(4, 4))
print("Original array:")
print(array)

# Replace all the elements in the third column with 0
for i in range(0,4):
    array[i, i] = 0
    i+=1
print("Modified array:")
print(array)

# Replace the diagonal elements with 0 (fill_diagonal numpy func)
np.fill_diagonal(array, 0)
print("Modified array with fill_diagonal:")
print(array)

Original array:
[[ 6 15 11  4]
 [ 2  1 10  1]
 [ 5  1 10  4]
 [ 4  6 12  3]]
Modified array:
[[ 0 15 11  4]
 [ 2  0 10  1]
 [ 5  1  0  4]
 [ 4  6 12  0]]
Modified array with fill_diagonal:
[[ 0 15 11  4]
 [ 2  0 10  1]
 [ 5  1  0  4]
 [ 4  6 12  0]]


### Assignment 2: Array Indexing and Slicing

1. Create a NumPy array of shape (6, 6) with values from 1 to 36. Extract the sub-array consisting of the 3rd to 5th rows and 2nd to 4th columns.

In [40]:
import numpy as np

# Create a NumPy array of shape (6, 6) filled with random integers
array = np.random.randint(1, 37, size=(5, 5))
print("Original array:")
print(array)

# Replace all the elements in the third column with 1
sub_array = array[2:5, 1:4]
print("Sub-array:")
print(sub_array)

Original array:
[[18  5  1 22 25]
 [30  8 12  9 13]
 [ 5 11 32 35 22]
 [12 13 23 29 31]
 [34  6  6 30 25]]
Sub-array:
[[11 32 35]
 [13 23 29]
 [ 6  6 30]]


2. Create a NumPy array of shape (5, 5) with random integers. Extract the elements on the border.

In [41]:
import numpy as np

# Create a NumPy array of shape (6, 6) filled with random integers
array = np.random.randint(1, 37, size=(5, 5))
print("Original array:")
print(array)

# Extract the elements on the border
border_elements = np.concatenate((array[0, :], array[-1, :], array[1:-1, 0], array[1:-1, -1]))
print("Border elements:")
print(border_elements)

Original array:
[[16 16 19 30  7]
 [ 5 10  8 32 18]
 [22 32 36 32 33]
 [ 5 22 29 16  4]
 [ 8 29 18 30  2]]
Border elements:
[16 16 19 30  7  8 29 18 30  2  5 22  5 18 33  4]


### Assignment 3: Array Operations

1. Create two NumPy arrays of shape (3, 4) filled with random integers. Perform element-wise addition, subtraction, multiplication, and division.

In [45]:
import numpy as np

array_1 = np.random.randint(1, 11, size=(3, 4))
print("Original first array:")
print(array_1)

array_2 = np.random.randint(1, 11, size=(3, 4))
print("Original second array:")
print(array_2)

add_array = array_1 + array_2
print("Addition:")
print(add_array)

sub_array = array_1 - array_2
print("Subtraction:")
print(sub_array)

mul_array = array_1 * array_2
print("Multiplication:")
print(mul_array)

div_array = array_1 / array_2
print("Division:")
print(div_array)

Original first array:
[[7 8 9 1]
 [2 1 8 2]
 [4 7 6 9]]
Original second array:
[[ 1  5 10  3]
 [ 1  4  6  3]
 [ 6  8  3  5]]
Addition:
[[ 8 13 19  4]
 [ 3  5 14  5]
 [10 15  9 14]]
Subtraction:
[[ 6  3 -1 -2]
 [ 1 -3  2 -1]
 [-2 -1  3  4]]
Multiplication:
[[ 7 40 90  3]
 [ 2  4 48  6]
 [24 56 18 45]]
Division:
[[7.         1.6        0.9        0.33333333]
 [2.         0.25       1.33333333 0.66666667]
 [0.66666667 0.875      2.         1.8       ]]


2. Create a NumPy array of shape (4, 4) with values from 1 to 16. Compute the row-wise and column-wise sum.


In [46]:
import numpy as np

array = np.random.randint(1, 17, size=(4, 4))
print("Original array:")
print(array)

# Compute the row-wise and column-wise sum
row_sum = np.sum(array, axis=1)
column_sum = np.sum(array, axis=0)

print("Row-wise sum:")
print(row_sum)
print("Column-wise sum:")
print(column_sum)

Original array:
[[14  4  3 12]
 [ 4  3  6 12]
 [ 7  7  4 12]
 [13  8 14  7]]
Row-wise sum:
[33 25 30 42]
Column-wise sum:
[38 22 27 43]


### Assignment 4: Statistical Operations

1. Create a NumPy array of shape (5, 5) filled with random integers. Compute the mean, median, standard deviation, and variance of the array.

In [54]:
import numpy as np

array = np.random.randint(1, 11, size=(5, 5))
print("Original array:")
print(array)

mean = np.mean(array)
print(f"Mean of array: {mean}")

median = np.median(array)
print(f"Median of array: {median}")

std_dev = np.std(array)
print(f"Standard deviation of array: {std_dev}")

vari = np.var(array)
print(f"Variance of array: {vari}")

Original array:
[[ 5  5  6  4  1]
 [ 5  1  5  8  6]
 [10  1  4  8  8]
 [ 4  2  5  8  4]
 [ 6  9  1  9  2]]
Mean of array: 5.08
Median of array: 5.0
Standard deviation of array: 2.6969612529660116
Variance of array: 7.273599999999999


2. Create a NumPy array of shape (3, 3) with values from 1 to 9. Normalize the array (i.e., scale the values to have a mean of 0 and a standard deviation of 1).

In [55]:
import numpy as np

array = np.random.randint(1, 10, size=(3, 3))
print("Original array:")
print(array)

# Normalize the array
mean = np.mean(array)
std_dev = np.std(array)
normalized_array = (array - mean) / std_dev

print("Normalized array:")
print(normalized_array)

Original array:
[[4 3 6]
 [2 7 1]
 [5 2 5]]
Normalized array:
[[ 0.05812382 -0.46499055  1.10435257]
 [-0.98810493  1.62746694 -1.5112193 ]
 [ 0.58123819 -0.98810493  0.58123819]]


### Assignment 5: Broadcasting

1. Create a NumPy array of shape (3, 3) filled with random integers. Add a 1D array of shape (3,) to each row of the 2D array using broadcasting.

In [57]:
# Create a NumPy array of shape (3, 3) filled with random integers
array = np.random.randint(1, 11, size=(3, 3))
row_array = np.random.randint(1, 11, size=(3,))
print("Original array:")
print(array)
print("1D array:")
print(row_array)

# Add the 1D array to each row of the 2D array using broadcasting
result = array + row_array
print("Resulting array:")
print(result)

Original array:
[[ 9  1 10]
 [ 9  4 10]
 [10  5  1]]
1D array:
[3 3 9]
Resulting array:
[[12  4 19]
 [12  7 19]
 [13  8 10]]


2. Create a NumPy array of shape (4, 4) filled with random integers. Subtract a 1D array of shape (4,) from each column of the 2D array using broadcasting.

In [58]:
# Create a NumPy array of shape (3, 3) filled with random integers
array = np.random.randint(1, 11, size=(4, 4))
column_array = np.random.randint(1, 11, size=(4,))
print("Original array:")
print(array)
print("1D array:")
print(row_array)

# Subtract the 1D array from each column of the 2D array using broadcasting
result = array - column_array[:, np.newaxis]
print("Resulting array:")
print(result)

Original array:
[[8 1 7 7]
 [7 7 3 5]
 [7 8 9 7]
 [2 1 5 4]]
1D array:
[3 3 9]
Resulting array:
[[ 2 -5  1  1]
 [ 3  3 -1  1]
 [-1  0  1 -1]
 [-5 -6 -2 -3]]


### Assignment 6: Linear Algebra

1. Create a NumPy array of shape (3, 3) representing a matrix. Compute its determinant, inverse, and eigenvalues.

In [59]:
# Create a NumPy array of shape (3, 3) representing a matrix
matrix = np.random.randint(1, 11, size=(3, 3))
print("Original matrix:")
print(matrix)

# Compute the determinant
determinant = np.linalg.det(matrix)
print("Determinant:", determinant)

# Compute the inverse
inverse = np.linalg.inv(matrix)
print("Inverse:")
print(inverse)

# Compute the eigenvalues
eigenvalues = np.linalg.eigvals(matrix)
print("Eigenvalues:", eigenvalues)

Original matrix:
[[3 7 3]
 [3 9 3]
 [9 2 1]]
Determinant: -48.00000000000003
Inverse:
[[-6.25000000e-02  2.08333333e-02  1.25000000e-01]
 [-5.00000000e-01  5.00000000e-01 -1.99840144e-17]
 [ 1.56250000e+00 -1.18750000e+00 -1.25000000e-01]]
Eigenvalues: [-2.32554796  1.49205212 13.83349584]


2. Create two NumPy arrays of shape (2, 3) and (3, 2). Perform matrix multiplication on these arrays.

In [60]:
# Create two NumPy arrays of shape (2, 3) and (3, 2)
array1 = np.random.randint(1, 11, size=(2, 3))
array2 = np.random.randint(1, 11, size=(3, 2))
print("Array 1:")
print(array1)
print("Array 2:")
print(array2)

# Perform matrix multiplication
result = np.dot(array1, array2)
print("Matrix multiplication result:")
print(result)

Array 1:
[[10  2  2]
 [ 5  8  9]]
Array 2:
[[7 9]
 [9 9]
 [6 1]]
Matrix multiplication result:
[[100 110]
 [161 126]]


### Assignment 7: Advanced Array Manipulation

1. Create a NumPy array of shape (3, 3) with values from 1 to 9. Reshape the array to shape (1, 9) and then to shape (9, 1).

In [67]:
# Create a NumPy array of shape (3, 3) with values from 1 to 9
array = np.arange(1, 10).reshape((3, 3))
print("Original array:")
print(array)

# Reshape the array to shape (1, 9)
resaped_arr_1 = array.reshape(1,9)
print("Reshaped to (1,9):")
print(resaped_arr_1)

# Reshape the array to shape (9, 1)
resaped_arr_2 = resaped_arr_1.reshape(9,1)
print("Reshaped to (9,1):")
print(resaped_arr_2)


Original array:
[[1 2 3]
 [4 5 6]
 [7 8 9]]
Reshaped to (1,9):
[[1 2 3 4 5 6 7 8 9]]
Reshaped to (9,1):
[[1]
 [2]
 [3]
 [4]
 [5]
 [6]
 [7]
 [8]
 [9]]


2. Create a NumPy array of shape (5, 5) filled with random integers. Flatten the array and then reshape it back to (5, 5).


In [72]:
array = np.random.randint(1, 11, size=(5, 5))
print("Original array:")
print(array)

flattened = array.flatten()
print("Flatten array:")
print(flattened)

reshaped = flattened.reshape(5,5)
print("Reshaped array:")
print(reshaped)

Original array:
[[ 4  2  2  1 10]
 [ 6  9  7  3  3]
 [ 8  3  1  2  5]
 [ 8  3  7  5  8]
 [ 5  2  8  2 10]]
Flatten array:
[ 4  2  2  1 10  6  9  7  3  3  8  3  1  2  5  8  3  7  5  8  5  2  8  2
 10]
Reshaped array:
[[ 4  2  2  1 10]
 [ 6  9  7  3  3]
 [ 8  3  1  2  5]
 [ 8  3  7  5  8]
 [ 5  2  8  2 10]]


### Assignment 8: Fancy Indexing and Boolean Indexing

1. Create a NumPy array of shape (5, 5) filled with random integers. Use fancy indexing to extract the elements at the corners of the array.

In [73]:
# Create a NumPy array of shape (5, 5) filled with random integers
array = np.random.randint(1, 21, size=(5, 5))
print("Original array:")
print(array)

# Use fancy indexing to extract the elements at the corners of the array
corners = array[[0, 0, -1, -1], [0, -1, 0, -1]]
print("Corner elements:")
print(corners)

Original array:
[[ 6  9  2 13 16]
 [ 7  9 16  6 10]
 [ 3  9 17 13  9]
 [ 6 11 16 12  5]
 [15  5  2 10  1]]
Corner elements:
[ 6 16 15  1]


2. Create a NumPy array of shape (4, 4) filled with random integers. Use boolean indexing to set all elements greater than 10 to 10.

In [74]:
# Create a NumPy array of shape (4, 4) filled with random integers
array = np.random.randint(1, 21, size=(4, 4))
print("Original array:")
print(array)

# Use boolean indexing to set all elements greater than 10 to 10
array[array > 10] = 10
print("Modified array:")
print(array)

Original array:
[[ 2 17 13 10]
 [13  8  9 20]
 [16  4 15 17]
 [12  7  9  3]]
Modified array:
[[ 2 10 10 10]
 [10  8  9 10]
 [10  4 10 10]
 [10  7  9  3]]


### Assignment 9: Structured Arrays

1. Create a structured array with fields 'name' (string), 'age' (integer), and 'weight' (float). Add some data and sort the array by age.

In [75]:
# Create a structured array with fields 'name', 'age', and 'weight'
data_type = [('name', 'U10'), ('age', 'i4'), ('weight', 'f4')]
data = np.array([('Alice', 25, 55.5), ('Bob', 30, 85.3), ('Charlie', 20, 65.2)], dtype=data_type)
print("Original array:")
print(data)

# Sort the array by age
sorted_data = np.sort(data, order='age')
print("Sorted array by age:")
print(sorted_data)

Original array:
[('Alice', 25, 55.5) ('Bob', 30, 85.3) ('Charlie', 20, 65.2)]
Sorted array by age:
[('Charlie', 20, 65.2) ('Alice', 25, 55.5) ('Bob', 30, 85.3)]


2. Create a structured array with fields 'x' and 'y' (both integers). Add some data and compute the Euclidean distance between each pair of points.

In [76]:
# Create a structured array with fields 'x' and 'y'
data_type = [('x', 'i4'), ('y', 'i4')]
data = np.array([(1, 2), (3, 4), (5, 6)], dtype=data_type)
print("Original array:")
print(data)

# Compute the Euclidean distance between each pair of points
distances = np.sqrt((data['x'][:, np.newaxis] - data['x'])**2 + (data['y'][:, np.newaxis] - data['y'])**2)
print("Euclidean distances:")
print(distances)

Original array:
[(1, 2) (3, 4) (5, 6)]
Euclidean distances:
[[0.         2.82842712 5.65685425]
 [2.82842712 0.         2.82842712]
 [5.65685425 2.82842712 0.        ]]


### Assignment 10: Masked Arrays

1. Create a masked array of shape (4, 4) with random integers and mask the elements greater than 10. Compute the sum of the unmasked elements.

In [77]:
import numpy.ma as ma

# Create a masked array of shape (4, 4) with random integers
array = np.random.randint(1, 21, size=(4, 4))
masked_array = ma.masked_greater(array, 10)
print("Original array:")
print(array)
print("Masked array:")
print(masked_array)

# Compute the sum of the unmasked elements
sum_unmasked = masked_array.sum()
print("Sum of unmasked elements:", sum_unmasked)

Original array:
[[15 18 14 12]
 [10  2 17 14]
 [17 12 20  9]
 [ 1  1 18  5]]
Masked array:
[[-- -- -- --]
 [10 2 -- --]
 [-- -- -- 9]
 [1 1 -- 5]]
Sum of unmasked elements: 28


2. Create a masked array of shape (3, 3) with random integers and mask the diagonal elements. Replace the masked elements with the mean of the unmasked elements.

In [78]:
# Create a masked array of shape (3, 3) with random integers
array = np.random.randint(1, 21, size=(3, 3))
masked_array = ma.masked_array(array, mask=np.eye(3, dtype=bool))
print("Original array:")
print(array)
print("Masked array:")
print(masked_array)

# Replace the masked elements with the mean of the unmasked elements
mean_unmasked = masked_array.mean()
masked_array = masked_array.filled(mean_unmasked)
print("Modified masked array:")
print(masked_array)

Original array:
[[ 6 15 19]
 [16 19  1]
 [10 15  7]]
Masked array:
[[-- 15 19]
 [16 -- 1]
 [10 15 --]]
Modified masked array:
[[12 15 19]
 [16 12  1]
 [10 15 12]]
